### ISSUE TITLE
Opponent's name wont display

### ISSUE THREAD

**Issue by herrlax** [nikteg/TDA367#17]
Whenever referring to getClient().getOpponents().get(0).getName() method returns "Player #opponent's ID" instead of opponent's name.

**Comment by thunef** [comment]
Why is this a bug? The default name of a player is "Player #opponent's ID".

**Comment by herrlax** [comment]
This rather displays a flaw in the server, where the server fails to update the players with its opponent's name, when a non-default name is set.
This will soon be solved in an upcoming feature.
