### ISSUE TITLE
invalid coordinates

### ISSUE THREAD

**Issue by herrlax** [nikteg/TDA367#18]
Sometimes an IllegalArgumentException is thrown when placing, even if coordinates is OK. Exception thrown in Coordinates class

**Comment by eineving** [comment]
Encountered an issue where where trying to place a rotated 4 ship in column 8 (close to the right side).Could be of use to this problem.

**Comment by herrlax** [comment]
Confirming that bug arises when placing a vertical ship in a way it wouldn't fit horizontally. Logic has to take in account for which rotation the ship has!
