### ISSUE TITLE
Package naming

### ISSUE THREAD

**Issue by nikteg** [nikteg/TDA367#2]
edu/chalmers/sankoss/java in desktop should be edu/chalmers/sankoss/**desktop**
edu/chalmers/sankoss/java in server should be edu/chalmers/sankoss/**server**

**Comment by herrlax** [comment]
We should as well change following packages starting with an upper case to a lower case:
desktop/src/main/java/edu/chalmers/sankoss/java/Inputs -> .../inputs
desktop/src/main/java/edu/chalmers/sankoss/java/Models -> .../models
desktop/src/main/java/edu/chalmers/sankoss/java/Renderers -> .../renderers

**Comment by herrlax** [comment]
This issue #2 was solved in commit e37dd9f671330ea007e394c2908301f4d392ff0f
