### ISSUE TITLE
Grids are vectors 100*1, not matrixes 10*10

### ISSUE THREAD

**Issue by eineving** [nikteg/TDA367#27]
The grid should be represented as table[10][10], not table[100] as they are now

**Comment by herrlax** [comment]
There's really no reason for this, since it's easier and more natural using nested for-loops (from 0-9) where outer loop (which is to be multiplied by 10 to represent the tens in vector) handles x-coordinate and inner loop handles y-coordinate (to represent the ones in vector)

**Comment by eineving** [comment]
Maybe we should rethink and not have any buttons at all

**Comment by herrlax** [comment]
Will close this issue now, after talk with our supervisor. We will use a vector and buttons.
