### ISSUE TITLE
Coordinates

### ISSUE THREAD

**Issue by eineving** [nikteg/TDA367#5]
How do we count our coordinates, is 1,1 in top left or bottom left?

**Comment by herrlax** [comment]
0, 0 is top left corner
9, 9 is bottom right

**Comment by eineving** [comment]
1,1 should be top left, 
10, 10 should be bottom right, mostly because thats how the user will see it and how we should display it.
Shall we discuss this on the next meeting?

**Comment by herrlax** [comment]
Ok, when handling coordinates visually for users 1,1 - 10,10 should be used and when handling coordinates internally 0,0 - 9,9 should be used.
